#!/bin/bash
# Copyright (c) 2016-2018 David Preece - davep@polymath.tech, All rights reserved.
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
clear
echo -------FILTER
sudo iptables -L -v -n
echo

echo -------NAT
sudo iptables -t nat -L -v -n
echo

for ctr in $(machinectl --no-legend list | cut -d' ' -f 1); do
    if [ "$ctr" == "No" ]; then
        exit 0
    fi
    echo -------$ctr
    pid=$(machinectl status $ctr | grep Leader | egrep -o '[0-9]*')
    sudo nsenter -t $pid -n iptables -L -v -n
    echo
    echo
done
